let numberBtn = document.querySelector('.number')
let operatorBtn = document.querySelector('.operator')
let clearBtn = document.getElementById('clear')
let DelBtn = document.getElementById('delete')
let equalBtn = document.getElementById('evaluate')
let pointBtn = document.getElementById('decimal')
let firstOperand = getElementById('firstOperand')
let secondOperand = getElementById('secondOperand')
